[phases.build]
cmd = "pip install -r requirements.txt"

[phases.start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --keep-alive 30"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "."
